# Generated by Django 6.0.3 on 2026-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20260410_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikiuser",
            options={
                "permissions": [
                    ("read", "Can read content"),
                    ("edit", "Can edit content"),
                    ("move", "Can move pages"),
                    ("delete", "Can delete pages"),
                    ("protect", "Can protect pages"),
                    ("import", "Can import data"),
                    ("export", "Can export data"),
                    ("block", "Can block users"),
                    ("unblock", "Can unblock users"),
                    ("email", "Can send email"),
                    ("upload", "Can upload files"),
                    ("edit-interface", "Can edit interface"),
                    ("edit-content-model", "Can edit content model"),
                    ("bot", "Is a bot"),
                    ("suppress", "Can suppress revisions"),
                    ("user-rights", "Can change user rights"),
                ]
            },
        ),
    ]
