# Generated by Django 6.0.3 on 2026-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("current_title", models.CharField(max_length=255, verbose_name="页面标题")),
                ("protection", models.CharField(default="", verbose_name="Protected")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "All Pages",
            },
        ),
        migrations.CreateModel(
            name="PageRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="Text")),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("suppressed", models.BooleanField(default=False, verbose_name="Suppressed")),
                ("created_at", models.DateTimeField()),
                (
                    "comment",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Edit comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision",
                "verbose_name_plural": "Revision list",
            },
        ),
        migrations.CreateModel(
            name="PageTitleIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Current Property Index",
                "verbose_name_plural": "Current Property Indices",
            },
        ),
        migrations.CreateModel(
            name="PropRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titles", models.JSONField(verbose_name="Page title")),
                ("content", models.JSONField(verbose_name="Property")),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("suppressed", models.BooleanField(default=False, verbose_name="Suppressed")),
                ("created_at", models.DateTimeField()),
                (
                    "comment",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Edit comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prop Revision",
                "verbose_name_plural": "Prop Revision list",
                "ordering": ["-id"],
            },
        ),
    ]
