# Generated by Django 6.0.3 on 2026-04-10 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagerevision",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="revision",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="pagerevision",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="revisions",
                to="core.page",
                verbose_name="Pageid related",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="current_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.pagerevision",
                verbose_name="Current revision",
            ),
        ),
        migrations.AddField(
            model_name="pagetitleindex",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_titles",
                to="core.page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="titles",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.pagetitleindex",
                verbose_name="Page title",
            ),
        ),
        migrations.AddField(
            model_name="proprevision",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="prop_revision",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="proprevision",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="prop_revisions",
                to="core.page",
                verbose_name="Pageid related",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="current_property_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.proprevision",
                verbose_name="Current property revision",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagetitleindex",
            unique_together={("page", "title")},
        ),
    ]
